NO MESSAGE SET

diff --git a/zipMod b/zipMod
--- a/zipMod
+++ b/zipMod
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 trap 'rm -f ./mod.7z' TERM
-./compile || exit 1
+./compile &>/dev/null || (
+  echo "fail exit"
+  exit 1
+)
 7zz a -mx9 -md64m mod.7z mathbreakers/BepInEx/plugins &>/dev/null
 echo mod.7z
 
